[test]
coverage = true
coverageSkipTestFiles = true
coverageThreshold = { lines = 0.9, functions = 0.9, statements = 0.9 }
coveragePathIgnorePatterns = [
  "src/utils/**",
  "src/database/**",
  "src/models/**",
  "src/interfaces/**",
  "src/dtos/**",
  "*.config.js"
]
coverageReporter  = ["text", "lcov"]
coverageDir = "./coverage"